src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity('email')]
#[ORM\EntityListeners(['App\EntityListener\UserListener'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\Email()]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    private ?string $plainPassword = null;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 2, max: 255)]
    private ?string $fullName = null;

    #[ORM\Column(length: 100, nullable: true)]
    #[Assert\Length(min: 2, max: 255)]
    private ?string $nickname = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Ingredient::class, orphanRemoval: true)]
    private Collection $Ingredients;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Recipe::class, orphanRemoval: true)]
    private Collection $recipes;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Mark::class, orphanRemoval: true)]
    private Collection $marks;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->updatedAt = new \DateTimeImmutable();
        $this->Ingredients = new ArrayCollection();
        $this->recipes = new ArrayCollection();
        $this->marks = new ArrayCollection();
    }

    #[ORM\PrePersist]
    public function setUpdatedAtvalue(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($plainPassword)
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFullName(): ?string
    {
        return $this->fullName;
    }

    public function setFullName(string $fullName): static
    {
        $this->fullName = $fullName;

        return $this;
    }

    public function getNickname(): ?string
    {
        return $this->nickname;
    }

    public function setNickname(?string $nickname): static
    {
        $this->nickname = $nickname;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Ingredient>
     */
    public function getIngredients(): Collection
    {
        return $this->Ingredients;
    }

    public function addIngredient(Ingredient $ingredient): static
    {
        if (!$this->Ingredients->contains($ingredient)) {
            $this->Ingredients->add($ingredient);
            $ingredient->setUser($this);
        }

        return $this;
    }

    public function removeIngredient(Ingredient $ingredient): static
    {
        if ($this->Ingredients->removeElement($ingredient)) {
            // set the owning side to null (unless already changed)
            if ($ingredient->getUser() === $this) {
                $ingredient->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Recipe>
     */
    public function getRecipes(): Collection
    {
        return $this->recipes;
    }

    public function addRecipe(Recipe $recipe): static
    {
        if (!$this->recipes->contains($recipe)) {
            $this->recipes->add($recipe);
            $recipe->setUser($this);
        }

        return $this;
    }

    public function removeRecipe(Recipe $recipe): static
    {
        if ($this->recipes->removeElement($recipe)) {
            // set the owning side to null (unless already changed)
            if ($recipe->getUser() === $this) {
                $recipe->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Mark>
     */
    public function getMarks(): Collection
    {
        return $this->marks;
    }

    public function addMark(Mark $mark): static
    {
        if (!$this->marks->contains($mark)) {
            $this->marks->add($mark);
            $mark->setUser($this);
        }

        return $this;
    }

    public function removeMark(Mark $mark): static
    {
        if ($this->marks->removeElement($mark)) {
            // set the owning side to null (unless already changed)
            if ($mark->getUser() === $this) {
                $mark->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Entity\Mark;
use App\Entity\Recipe;
use App\Form\MarkType;
use App\Form\RecipeType;
use App\Repository\MarkRepository;
use App\Repository\RecipeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

#[Route('/recipe', name: 'recipe')]
#[IsGranted('ROLE_USER')]
class RecipeController extends AbstractController
{
    #[Route('/', name: '_index', methods:['GET'])]
    public function index(RecipeRepository $recipeRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $recipes = $paginator->paginate(
            $recipeRepository->findBy(['user' => $this->getUser()]),
            $request->query->getInt('page', 1),
            10
        );

        return $this->render('pages/recipe/index.html.twig', [
            'recipes' => $recipes,
        ]);
    }

    #[Route('/show/{id}', name:'_show', methods:['GET', 'POST'])]
    #[Security("is_granted('ROLE_USER') and recipe.isIsPublic() === true")]
    public function show(Recipe $recipe, Request $request, MarkRepository $markRepository, EntityManagerInterface $em): Response
    {
        $mark = new Mark();

        $form = $this->createForm(MarkType::class, $mark);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

            $mark->setUser($this->getUser())
                ->setRecipe($recipe);

            $existingMark = $markRepository->findOneBy([
                'user' => $this->getUser(),
                'recipe' => $recipe
            ]);

            if(!$existingMark) {
                $em->persist($mark);
            } else {
                $existingMark->setMark(
                    $form->getData()->getMark()
                );
            }

            $em->flush();

            $this->addFlash('success', 'Nota adicionada com sucesso!');
            return $this->redirectToRoute('recipe_show', ['id' => $recipe->getId()]);
        }

        return $this->render('pages/recipe/show.html.twig', [
            'recipe' => $recipe,
            'form' => $form->createView()
        ]);
    }

    #[Route('/publish', name:'_index_public', methods:['GET'])]
    public function indexPublic(RecipeRepository $recipeRepository): Response
    {

        return $this->render('pages/recipe/index_public.html.twig', [
            'recipes' => $recipeRepository->findPublicRecipe(100),
        ]);
    }

    #[Route('/new', name:'_new', methods:['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $em): Response
    {
        $recipe = new Recipe();
        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $recipe = $form->getData();
            $recipe->setUser($this->getUser());

            $em->persist($recipe);
            $em->flush();

            $this->addFlash('success', 'receita criado com sucesso!');
            return $this->redirectToRoute('recipe_index');
        }

        return $this->render('pages/recipe/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/edit/{id<\d+>}', name:'_edit', methods:['GET', 'POST'])]
    #[Security("is_granted('ROLE_USER') and user === recipe.getUser()")]
    public function edit(Recipe $recipe, Request $request, EntityManagerInterface $em): Response {

        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $recipe = $form->getData();

            $em->persist($recipe);
            $em->flush();

            $this->addFlash('success', 'Receita editada com sucesso!');
            return $this->redirectToRoute('recipe_index');
        }

        return $this->render('pages/recipe/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/delete/{id<\d+>}', name:'_delete', methods:['POST'])]
    #[Security("is_granted('ROLE_USER') and user === recipe.getUser()")]
    public function delete(Request $request, Recipe $recipe, RecipeRepository $recipeRepository): Response {

        if ($this->isCsrfTokenValid('delete'.$recipe->getId(), $request->request->get('_token'))) {

            $recipeRepository->remove($recipe, true);
            $this->addFlash('success', 'Receita excluida com sucesso!');
        }
        return $this->redirectToRoute('recipe_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/pages/recipe/_delete_form.html.twig
<form method="post" action="{{ path('recipe_delete', {'id': recipe.id}) }}" onsubmit="return confirm('Tem certeza de que deseja excluir este item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recipe.id) }}">
    <button class="btn btn-sm btn-outline-danger">Excluir</button>
</form>

templates/pages/recipe/edit.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="container">
        <h1 class="mt-4">Editar receita</h1>
    </div>
    <div class="container mt-4">


        {{ form_start(form) }}
            {{ form_errors(form) }}

            <div class="form-group">
                {{ form_label(form.name) }}
                {{ form_widget(form.name) }}
                <div class="form-error text-danger">
                    {{ form_errors(form.name) }}
                </div>
            </div>

            <div class="form-group">
                {{ form_label(form.time) }}
                {{ form_widget(form.time) }}
                <div class="form-error text-danger">
                    {{ form_errors(form.time) }}
                </div>
            </div>

            <div class="form-group">
                {{ form_label(form.nbPeople) }}
                {{ form_widget(form.nbPeople) }}
                <div class="form-error text-danger">
                    {{ form_errors(form.nbPeople) }}
                </div>
            </div>

            <div class="form-group">
                {{ form_label(form.difficulty) }}
                {{ form_widget(form.difficulty) }}
                <div class="form-error text-danger">
                    {{ form_errors(form.difficulty) }}
                </div>
            </div>

            <div class="form-group">
                {{ form_label(form.description) }}
                {{ form_widget(form.description) }}
                <div class="form-error text-danger">
                    {{ form_errors(form.description) }}
                </div>
            </div>

            <div class="form-group">
                {{ form_label(form.price) }}
                {{ form_widget(form.price) }}
                 <div class="form-error text-danger">
                    {{ form_errors(form.price) }}
                </div>
            </div>

            <fieldset class="form-group mt-4">
                <div class="form-check">
                    {{ form_widget(form.isFavorite) }}
                    {{ form_label(form.isFavorite) }}
                    <div class="form-error text-danger">
                        {{ form_errors(form.isFavorite) }}
                    </div>
                </div>
            </fieldset>

            {{ form_row(form.imageFile) }}

            <div class="form-group">
                {{ form_label(form.ingredients) }}
                {{ form_widget(form.ingredients) }}
                 <div class="form-error text-danger">
                    {{ form_errors(form.ingredients) }}
                </div>
            </div>

            <div class="form-group">
                {{ form_row(form.submit) }}
            </div>

        {{ form_end(form) }}

    </div>
{% endblock %}

templates/pages/recipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SF-Recipes - Minhas receitas{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="mt-4">Minhas Receitas</h1>

        <div class="d-flex justify-content-end">
            <a href="{{ path('recipe_new') }}" class="btn btn-primary">Nova Receita</a>
        </div>

        <div class="count d-flex justify-content-end mt-4">
            <h4>
                {{ recipes|length > 0 ? recipes.getTotalItemCount : "0" }} receitas ao total
            </h4>
        </div>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Preço</th>
                    <th scope="col">Dificuldade</th>
                    <th scope="col">Cadastro</th>
                    <th scope="col"></th>
                </tr>

            </thead>
            <tbody>
                {% for recipe in recipes %}

                    <tr class="table-light">
                        <th scope="row">{{ recipe.id }}</th>
                        <td>{{ recipe.name }}</td>
                        <td>{{ recipe.price is not null ? recipe.price|format_currency('BRL') : ' Não informado ' }}</td>
                        <td>
                            <div class="progress" role="progressbar" aria-label="Example with label" aria-valuenow="{{ recipe.difficulty }}" aria-valuemin="1" aria-valuemax="6">
                                <div class="progress-bar" style="width: {{ ((recipe.difficulty * 100) / 6) }}%">{{ recipe.difficulty }}</div>
                            </div>
                        </td>
                        <td>{{ recipe.createdAt|date('d/m/Y') }}</td>
                        <td>
                            <div class="d-flex flex-row gap-3">
                                {{ include('pages/recipe/_delete_form.html.twig') }}
                                <a href="{{ path('recipe_edit', {id: recipe.id}) }}" class="btn btn-sm btn-outline-info">Editar</a>
                            </div>
                        </td>
                    </tr>
                {% else %}
                    <tr class="table-ligth">
                        <th colspan="4">
                            Nenhuma receita cadastrada
                        </th>
                    </tr>
                {% endfor %}

            </tbody>
        </table>
        <div class="navigation d-flex justify-content-center">
            {% if recipes|length > 0 %}
                {{ knp_pagination_render(recipes) }}
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/pages/recipe/index_public.html.twig
{% extends "base.html.twig" %}

{% block base %}
     <div class="container">
        <h1 class="mt-4">Receitas da comunidade</h1>

        <div class="d-flex justify-content-end">
            <a href="{{ path('recipe_new') }}" class="btn btn-primary">Nova Receita</a>
        </div>

        <div class="count d-flex justify-content-end mt-4">
            <h4>
                {{ recipes|length > 0 ? recipes.getTotalItemCount : "0" }} receitas ao total
            </h4>
        </div>

        <div class="row">

            {% for recipe in recipes %}

                <div class="card border-primary col-12 col-sm-6 col-md-4 col-lg-3 mb-3">
                    <div class="card-header">{{ 'Receita n° ' ~ recipe.id }}</div>
                    <div class="card-body">
                        <h4 class="card-title">{{ recipe.name }}</h4>
                        <p class="card-text">
                            {{ recipe.description|slice(0, 100) ~ '...' }}
                        </p>
                    </div>
                </div>
            {% else %}
                <div class="card border-primary col-12 col-sm-6 col-md-4 col-lg-3 mb-3">
                    <div class="card-body">
                        <h4 class="card-title">Nenhuma receita disponível</h4>
                        <p class="card-text"></p>
                    </div>
                </div>asdasd
            {% endfor %}
        </div>

        <div class="navigation d-flex justify-content-center">
            {% if recipes|length > 0 %}
                {{ knp_pagination_render(recipes) }}
            {% endif %}
        </div>

    </div>
{% endblock %}

templates/pages/recipe/new.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="container">
        <h1 class="mt-4">Adicionar nova receita</h1>
    </div>
    <div class="container mt-4">

        {{ form_start(form) }}
            {{ form_errors(form) }}

            <div class="form-group">
                {{ form_label(form.name) }}
                {{ form_widget(form.name) }}
                <div class="form-error text-danger">
                    {{ form_errors(form.name) }}
                </div>
            </div>

            <div class="form-group">
                {{ form_label(form.time) }}
                {{ form_widget(form.time) }}
                <div class="form-error text-danger">
                    {{ form_errors(form.time) }}
                </div>
            </div>

            <div class="form-group">
                {{ form_label(form.nbPeople) }}
                {{ form_widget(form.nbPeople) }}
                <div class="form-error text-danger">
                    {{ form_errors(form.nbPeople) }}
                </div>
            </div>

            <div class="form-group">
                {{ form_label(form.difficulty) }}
                {{ form_widget(form.difficulty) }}
                <div class="form-error text-danger">
                    {{ form_errors(form.difficulty) }}
                </div>
            </div>

            <div class="form-group">
                {{ form_label(form.description) }}
                {{ form_widget(form.description) }}
                <div class="form-error text-danger">
                    {{ form_errors(form.description) }}
                </div>
            </div>

            <div class="form-group">
                {{ form_label(form.price) }}
                {{ form_widget(form.price) }}
                 <div class="form-error text-danger">
                    {{ form_errors(form.price) }}
                </div>
            </div>

            <fieldset class="form-group mt-4">
                <div class="form-check">
                    {{ form_widget(form.isFavorite) }}
                    {{ form_label(form.isFavorite) }}
                    <div class="form-error text-danger">
                        {{ form_errors(form.isFavorite) }}
                    </div>
                </div>
            </fieldset>

            {{ form_row(form.imageFile) }}

            <div class="form-group">
                {{ form_label(form.ingredients) }}
                {{ form_widget(form.ingredients) }}
                 <div class="form-error text-danger">
                    {{ form_errors(form.ingredients) }}
                </div>
            </div>

            <div class="form-group">
                {{ form_row(form.submit) }}
            </div>

        {{ form_end(form) }}
    </div>
{% endblock %}

templates/pages/recipe/show.html.twig
{% extends "base.html.twig" %}

{% block body %}

    <div class="container">
        <h1 class="mt-4">{{ recipe.name }}</h1>

        <div class="recipe__image">
            <img src="{{ vich_uploader_asset(recipe, 'imageFile') }}" alt="...">
        </div>

        <p>Média de nota da receita {{ recipe.average }} / 5</p>
        <span class="badge bg-primary">Criado em {{ recipe.createdAt|date('d/m/Y') }}</span>

        <ul class="list-group list-group-flush mt-4">
            <li class="list-group-item">
                {% if recipe.time %}
                    Tempo (em minutos): {{ recipe.time }}
                {% else %}
                    Tempo (em minutos) não definido
                {% endif %}
            </li>
            <li class="list-group-item">
                {% if recipe.nbPeople %}
                    Para: {{ recipe.nbPeople }} pessoas
                {% else %}
                    Quantidade de pessoas não definidas
                {% endif %}
            </li>
            <li class="list-group-item">
                {% if recipe.difficulty %}
                    Dificuldade: {{ recipe.difficulty }}
                {% else %}
                    Dificuldade não definida
                {% endif %}
            </li>
            <li class="list-group-item">
                {% if recipe.price %}
                    Valor (R$): {{ recipe.price|number_format(2, ',', '.') }}
                {% else %}
                    Valor não definido
                {% endif %}
            </li>
        </ul>

        <div>
            {{ recipe.description|raw }}
        </div>

        <h4 class="mt-4 text-primary">Ingredientes</h4>

        {% for ingredient in recipe.ingredients %}
            <span class="badge bg-primary">{{ ingredient.name }}</span>
        {% endfor %}


        <div class="mark">
            {{ form(form) }}
        </div>

    </div>

{% endblock %}